### ISSUE TITLE
load content 、虚拟滚动逻辑解耦

### ISSUE THREAD

**Issue by sunshinesmilelk** [difizen/libro#225]
1. 解耦在load content 中才给 jupyterModel 属性赋值、启动kernel connection 的逻辑。
2. 虚拟滚动逻辑强依赖在每种 cell 的 react 组件中，以及目前部分cell 有虚拟滚动、部分没有

**Comment by BroKun** [comment]
虚拟滚动是一个交互能力，不是一个数据能力，本来就是要跟每一种交互能力的具体需然实现相关的。允许 cell 不实现相关能力就可以了。

**Comment by sunshinesmilelk** [comment]
> 虚拟滚动是一个交互能力，不是一个数据能力，本来就是要跟每一种交互能力的具体需然实现相关的。允许 cell 不实现相关能力就可以了。

有的cell 实现了计算虚拟滚动高度等的逻辑，有的cell没有实现，可以想象一下最终触发虚拟滚动时的画面

**Comment by BroKun** [comment]
真正处理的时候再重新打开
