### ISSUE TITLE
[bug] libro在Windows11系统下使用终端出现的问题

### ISSUE THREAD

**Issue by MaxforCherubim** [difizen/libro#248]
- 我起初用mac使用libro，体验很好，也习惯与在libro中开多个终端。同时还发现多个终端其实都保存在**运行的终端**中，即使关闭终端页面也仍然可以再度点开。
- 等我需要使用公司Win11电脑时，发现libro多开终端，关闭再打开的操作不行了。

![{78B6D4A8-8FDD-4AA3-B58F-AA6AAA88C30C}](https://github.com/user-attachments/assets/95bec585-bdef-494e-ad53-7d3bf5bef30a)
关闭了页面后，打不开也算了，关也关不掉。

- 当然这些都是小问题，就式反馈一下issues，总体体验很好，很丝滑，给人一种现代化的感觉！

**Comment by BroKun** [comment]
我在机器上验证了一下，windows 下 terminal 重连是正常的，但是关闭是有问题的。
jupyterlab 这边目前也有一样的问题，https://github.com/jupyterlab/jupyterlab/issues/5061

然后我们定位了一下 terminal 删除问题，出在比较底层，jupyter 服务尝试让 terminal 跟实际的进程状态始终一致，但是在 windows 上有意外情况。如果你是比较长时间不用然后重连失败，可能 terminal 本身状态也异常了，这种情况在 linux 下可以直接反馈在产品上，比如进程删除了，但是 windows 下有异常。

如果我们产品上忽略掉这种状态的  terminal，可能会有内存泄露风险，我需要再评估一下，但是有可能短时间解决不了这个问题。
