### ISSUE TITLE
[feature] 报错信息的改进

### ISSUE THREAD

**Issue by MaxforCherubim** [difizen/libro#253]
- 看样子libro会将报错信息提取输出成更合适的内容
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/1eec0422-c526-4e1d-9f42-68e56e8dee55">

- 同时括号内的 **130\*.py** 似乎提示了jupyter单元格运行的本质
- 我不懂jupyter黑盒下是怎么运行，不过是否可以有选项将 **130\*.py** 改为正常的Cell In[ ]?
![b645d3b3ce07df76468caf6e8d7a53d9](https://github.com/user-attachments/assets/d1a3a8ba-a6e8-4a66-8d44-e2e3a142dd23)

**Comment by sunshinesmilelk** [comment]
1. jupyter server 侧对报错进行了一次提取，evalue和traceback,您提到的 Cell In[ ]是在traceback中，但是 traceback有可能内容会很多。
2. libro 在错误显示时进行了UI交互上的优化，展示错误时首先展示 evalue，只有展示错误详情时会展示对应的 traceback。
3. 因此 libro 客户端侧不太好做到您这边说的有选项将 130*.py 改为正常的Cell In[ ]

**Comment by MaxforCherubim** [comment]
感谢回复！
确实遇上复杂报错，traceback没这么简单。
事实上130*.py这样的提示信息应该没人看吧，主要看后面的line 1提示。
