### ISSUE TITLE
[feature] Libro能否添加新kernel？

### ISSUE THREAD

**Issue by MaxforCherubim** [difizen/libro#256]
- 有的时候我会使用jupyter lab的IRkernel和xeus-sql kernel来写一些R和SQL的笔记本
- 请问在jupyter的kernel基础上添加R和SQL的kernel是否是合理的？

**Comment by BroKun** [comment]
libro 本身兼容 ipython 的任意 kernel，所以在 libro 中使用 R kernel 是可行的，但是也有如下问题：
* 目前 libro 的代码都通过 python cell 来完成，内置了不少 python 语言支持，对其他语言的支持还没有
* 由于 jupyter 的文档格式是 code cell 形态，并没有区分到具体语言，所以在 libro 支持 R 或者 SQL 的情况下，可能也需要拓展一下代码定义，文档或者 cell 级别 meta 中增加对首选语言的指定。
* sql 方言比较多，我们有处理 sql 的很多经验，但是目前并不打算做的太重。

libro 团队目前的主要在处理 python 和 AI 方向的特性，后面我们会在社区里公开我们的路线图。R/SQL 也可以放进来讨论。

**Comment by BroKun** [comment]
![image](https://github.com/user-attachments/assets/31b9b20f-c1e1-4f35-a3c0-d140d4fa717d)

![image](https://github.com/user-attachments/assets/b2f7e0ee-f5e0-4df9-99e5-1bd815306501)

增加 R kernel 后的使用情况如图
