### ISSUE TITLE
[bug] md单元格写标题，同时根据标题折叠单元格后，创建新单元格错位

### ISSUE THREAD

**Issue by MaxforCherubim** [difizen/libro#261]
## bug描述

- 使用md单元格写二级标题，然后折叠其对应单元格相信是很多人写类notebook的习惯
- 现在在libro使用这种范式时，通过点击单元格间的间隙创建新单元格时（如下图）
![image](https://github.com/user-attachments/assets/7a234456-9820-4561-8d2d-4de51ed32829)

    会发生错位，创建到其他位置了

## 复现过程

这是我出现bug的笔记本 [issue.zip](https://github.com/user-attachments/files/17413565/issue.zip)

- 当我打开该笔记本时，把所有md标题单元格都折叠，当然最后一个md标题单元格就不用折叠了，不然全部单元格都折叠了。
- 在未折叠的后面的单元格间隔间点击创建新单元格时，将会发生bug，理应插入其中的单元格直接跑到上面的错误位置了。（如下gif）
![issue](https://github.com/user-attachments/assets/4b969bd9-3361-452f-aa27-8dcf84269ff3)

**Comment by BroKun** [comment]
Fixed in the 0.2.42 release.
